### ISSUE TITLE
Flycheck does not refresh errors when other files have changed

### ISSUE THREAD

**Issue by Dushistov** [flycheck/flycheck-rust#56]
Let we have crate without any dependicies and one module `mod1`.

```
$ cargo new --lib foo
$ cd foo/src
$ cat > lib.rs
mod mod1;
Ctrl+D
$ cat > mod1.rs
fn f() {
    debug!("begin");
}
Ctrl+D
```

if we open `mod1.rs` into emacs it shows error:
`cannot find macro debug`

after that we can fix this error by adding:
```
[dependencies]
log = "0.3.6"
```
to `Cargo.toml`
and 
```
#[macro_use]
extern crate log;
```
to `src/lib.rs`

but after all manipulation, and successefull run of `cargo check|build|test`,
if come back to `mod1.rs` it still show error.

Because of `mod1.rs` not changed,
the same thing should happen and without macros I suppose,
for example if we first type `use modX:::func;` and only then add `modX` to crate and implement
`func`

So It would be nice rerun syntax check if `Cargo.toml` or `lib.rs|main.rs` changed on disk.

**Comment by Dushistov** [comment]
>So It would be nice rerun syntax check if Cargo.toml or lib.rs|main.rs changed on disk.

This is minimum, I suppose, for 100% correct results flycheck-rust need rerun check if any
".rs" + Cargo.toml file changed on disk.

**Comment by fmdkdd** [comment]
Ah yes, well I'm afraid you've hit a Flycheck limitation here.  Flycheck works per-buffer, not per-project.  That means that if buffer A has an error that can be fixed by editing buffer B, Flycheck has no knowledge that editing B should re-trigger a syntax check in A.

This is not rust-specific; the same happens when checking C, where if you have an error in `foo.c` that can be fixed by going into `foo.h`, after the change in `foo.h`, the error will still be here in `foo.c`.  You have to trigger a syntax check in `foo.c` for the error to disappear.

I guess you could workaround this limitation by telling Flycheck to trigger a syntax check whenever you edit a `.rs` or `Cargo.toml` file in the same project, like you said.  You should be able to do that with `after-save-hook` for instance.

In general, I don't think we want to change this behavior in Flycheck at the moment.  But if someone were to find a way to do it without adding too much complexity, they would be welcome to send a PR to https://github.com/flycheck/flycheck ;)

However, for Rust, there is another solution on the horizon: to use [rustls](https://github.com/rust-lang-nursery/rls), which has knowledge of the whole project.

**Comment by peterwvj** [comment]
@fmdkdd Can you please clarify? Is there an easy to run the syntax checker on file `B` whenever changes are made to file `A`? I may be missing something but it seems like `flycheck-buffer` is the only way to manually trigger a syntax check. However, this functions runs the syntax checker on the current buffer. Perhaps, what we need is a function `flycheck-buffer` that receives the buffer to run the syntax checker on as input. What do you think?

**Comment by fmdkdd** [comment]
> Perhaps, what we need is a function flycheck-buffer that receives the buffer to run the syntax checker on as input. 

That's not necessary.  You can just do `(with-current-buffer B (flycheck-buffer))`.

> Is there an easy way to run the syntax checker on file B whenever changes are made to file A? 

Evaluate this in A:

```emacs-lisp
(add-hook after-change-functions 
  (lambda (_beg _end _len) 
    (with-current-buffer B (flycheck-buffer)))
   nil 'local)
```

Now you could go further and look at the project, build a graph of file dependencies, and trigger a check in dependent files whenever an upstream file is changed.  That logic would be language-specific, at best.

In the meantime, we have flycheck/flycheck#1308 which should soon be merged.

**Comment by peterwvj** [comment]
Great, thanks for explaining!

**Comment by fmdkdd** [comment]
Closing as won't fix for now.  Though flycheck has gained the ability to recheck buffer on switch, so look into that.
